[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ChengMingLiew", email = "125233730+ChengMingLiew@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "celery>=5.6.3",
    "fastapi>=0.141.1",
    "fastapi-users[sqlalchemy]>=15.0.5",
    "flower>=2.2.0",
    "psycopg[binary]>=3.3.6",
    "pydantic-settings>=2.15.0",
    "pynacl>=1.6.2",
    "redis>=8.1.0",
    "sqlalchemy>=2.0.54",
    "up-bank-sdk>=0.3.0",
    "uvicorn[standard]>=0.53.0",
]

[project.scripts]
api = "api:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.9",
]
